/*
 * This source file was generated by the Gradle 'init' task
 */
package jif2;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        SaySomethingAnonymousClass s = new SaySomethingAnonymousClass();
        System.out.println("english:" + s.sayStuffAmericanEnglish());
        System.out.println("spanish:" + s.sayStuffSpanish());
    }
}
