/*
 * This source file was generated by the Gradle 'init' task
 */
package jif;

public class App {
    public String getGreeting() {
        return "Let's play some music!";
    }

    // Inner class
    class Combo {
        private MakesSound[] guitars;
        private MakesSound bass;

        public Combo(MakesSound[] guitars, MakesSound bass) {
            this.guitars = guitars;
            this.bass = bass;
        }

        public String play() {
            if ((guitars == null || guitars.length == 0) && bass == null) {
                return "No instruments to play.";
            }
            StringBuilder sb = new StringBuilder();
            for (MakesSound guitar : guitars) {
                sb.append(guitar.getSound()).append(" ");
            }
            sb.append(bass.getSound());
            return(sb.toString().trim());
        }      
        public int getNumberOfMembers() {
            return (guitars != null ? guitars.length : 0)  + (bass != null ? 1 : 0); // +1 for the bass
        }  
    }

    public Combo createCombo(MakesSound[] guitars, MakesSound bass) {
        return new Combo(guitars, bass);
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Combo combo = new App().createCombo(
            new MakesSound[] { new Guitar(), new Guitar() },
            new Bass()
        );
        combo.play();
    }
}
