/*
 * This source file was generated by the Gradle 'init' task
 */
package jif2;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void testSayStuffAmericanEnglish() {
        SaySomethingAnonymousClass s = new SaySomethingAnonymousClass();
        String result = s.sayStuffAmericanEnglish();
        assertEquals("Hello! Goodbye! My favorite movie is Spinal Tap.", result);
    }

    @Test void testSayStuffSpanish() {
        SaySomethingAnonymousClass s = new SaySomethingAnonymousClass();
        String result = s.sayStuffSpanish();
        assertEquals("Hola! Despedida! Mi película favorita es Spinal Tap.", result);
    }
}
