/*
 * This source file was generated by the Gradle 'init' task
 */
package jif;

import org.junit.jupiter.api.Test;

import jif.App.Combo;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void testComboWithMembers() {
        App classUnderTest = new App();
        Combo combo = classUnderTest.createCombo(
            new MakesSound[] { new Guitar(), new Guitar() },
            new Bass()
        );
        String playSounds = combo.play();
        assertNotEquals("No instruments to play.", playSounds, "play() should return some sounds when instruments are present");
    }

     @Test void testComboWithOutMembers() {
        App classUnderTest = new App();
        Combo combo = classUnderTest.createCombo(
            new MakesSound[] { },
            null
        );
        String playSounds = combo.play();
        assertEquals("No instruments to play.", playSounds, "Empty Combo should return No instruments to play");
    }
}
